# Generated by Django 2.1.1 on 2018-11-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='time',
            new_name='start_time',
        ),
    ]
