# Generated by Django 2.1.1 on 2018-11-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_auto_20181106_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='duration',
            new_name='end_time',
        ),
    ]
