# Generated by Django 2.1.1 on 2018-10-27 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubenrollment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Registered_User'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='club_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Registered_User'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Registered_User'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Registered_User'),
        ),
    ]
