# Generated by Django 2.1.1 on 2018-10-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered_college',
            name='Password',
        ),
    ]
