# Generated by Django 2.1.2 on 2018-11-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered_college',
            name='role',
        ),
    ]
