# Generated by Django 2.1.2 on 2018-11-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181118_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered_user',
            name='Unique_Id',
        ),
    ]
