# Generated by Django 2.1.2 on 2018-10-31 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_registered_college_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered_college',
            old_name='Email_Id',
            new_name='Email',
        ),
    ]
