# Generated by Django 2.1.2 on 2018-11-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181101_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered_college',
            old_name='Email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='registered_college',
            name='College_Registration_Number',
            field=models.IntegerField(default=0),
        ),
    ]
