# Generated by Django 2.1.2 on 2018-11-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181101_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_college',
            name='College_Registration_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registered_college',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
