# Generated by Django 2.1.2 on 2018-11-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181102_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_college',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
