# Generated by Django 2.1.2 on 2018-11-03 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20181103_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=500)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Registered_User')),
            ],
        ),
    ]
