# Generated by Django 2.1.2 on 2018-11-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Post')),
            ],
        ),
    ]
